apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: &app bandit
  namespace: datasci
  annotations:
    postgres.db.movetokube.com/instance: datasci
spec:
  database: *app
---
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: &app bandit
  namespace: datasci
  annotations:
    postgres.db.movetokube.com/instance: datasci
spec:
  role: *app
  database: *app
  secretName: database
  privileges: OWNER
