apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bandit
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/datasci/bandit/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: bandit
  wait: true
  timeout: 5m
