apiVersion: v1
kind: Service
metadata:
  name: bandit-pipeline
  namespace: datasci
  labels:
    app.kubernetes.io/name: bandit
    app.kubernetes.io/component: pipeline
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bandit
    app.kubernetes.io/component: pipeline
  ports:
    - name: grpc
      port: 4000
      targetPort: grpc
      protocol: TCP
