apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - db/postgres.yaml
  - pipeline/deployment.yaml
  - pipeline/service.yaml
  - service/deployment.yaml
  - service/service.yaml
  - service/ingress.yaml
  - seldon/seldondeployment.yaml
