apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bandit-service
  namespace: datasci
spec:
  ingressClassName: internal
  rules:
    - host: bandit.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bandit-service
                port:
                  number: 8000
